/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface GameProgress {
  'quizScoresPerLevel' : Array<[bigint, bigint]>,
  'userId' : Principal,
  'currentLevel' : bigint,
  'unlockedLevels' : Array<bigint>,
  'completedLevels' : Array<bigint>,
}
export interface Note {
  'id' : bigint,
  'subject' : Subject,
  'blob' : ExternalBlob,
  'description' : string,
  'fileName' : string,
  'uploadedBy' : Principal,
}
export interface PomodoroSettings { 'focusTime' : bigint, 'breakTime' : bigint }
export interface Question {
  'text' : string,
  'correctAnswerIndex' : bigint,
  'options' : Array<string>,
}
export interface Quiz {
  'id' : bigint,
  'title' : string,
  'subject' : Subject,
  'questions' : Array<Question>,
}
export interface QuizResult {
  'userId' : Principal,
  'answers' : Array<bigint>,
  'score' : bigint,
  'totalQuestions' : bigint,
  'timestamp' : bigint,
  'quizId' : bigint,
}
export interface StudyPlan {
  'timetable' : string,
  'subjects' : Array<Subject>,
  'timeSlots' : Array<string>,
  'userId' : Principal,
}
export interface StudyTip {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'subject' : Subject,
}
export type Subject = { 'reading' : null } |
  { 'socialStudies' : null } |
  { 'math' : null } |
  { 'grammar' : null } |
  { 'science' : null };
export interface UserProfile {
  'name' : string,
  'role' : string,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addNote' : ActorMethod<[ExternalBlob, Subject, string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'completeSubjectChallenge' : ActorMethod<[string], undefined>,
  'createQuiz' : ActorMethod<[string, Subject, Array<Question>], bigint>,
  'createStudyPlan' : ActorMethod<
    [Array<Subject>, Array<string>, string],
    undefined
  >,
  'createStudyTip' : ActorMethod<[string, string, Subject], bigint>,
  'deleteNote' : ActorMethod<[bigint], undefined>,
  'deleteQuiz' : ActorMethod<[bigint], undefined>,
  'deleteStudyTip' : ActorMethod<[bigint], undefined>,
  'getAdminStatistics' : ActorMethod<
    [],
    {
      'totalStudyTips' : bigint,
      'totalQuizzes' : bigint,
      'totalNotes' : bigint,
      'totalUsers' : bigint,
    }
  >,
  'getAllNotes' : ActorMethod<[], Array<Note>>,
  'getAllQuizzes' : ActorMethod<[], Array<Quiz>>,
  'getAllStudyTips' : ActorMethod<[], Array<StudyTip>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getGameProgress' : ActorMethod<[], [] | [GameProgress]>,
  'getGameScores' : ActorMethod<[], Array<bigint>>,
  'getLeaderboard' : ActorMethod<[], Array<[Principal, bigint]>>,
  'getNotesBySubject' : ActorMethod<[Subject], Array<Note>>,
  'getOverallProgress' : ActorMethod<
    [],
    {
      'quizScores' : Array<bigint>,
      'gameProgressData' : [] | [GameProgress],
      'studyHours' : bigint,
    }
  >,
  'getPomodoroSettings' : ActorMethod<[], PomodoroSettings>,
  'getQuizResultsForQuiz' : ActorMethod<[bigint], Array<QuizResult>>,
  'getQuizResultsForUser' : ActorMethod<[], Array<QuizResult>>,
  'getQuizzesBySubject' : ActorMethod<[Subject], Array<Quiz>>,
  'getStudyPlan' : ActorMethod<[], [] | [StudyPlan]>,
  'getStudyTipsBySubject' : ActorMethod<[Subject], Array<StudyTip>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'hasCompletedSubjectChallenge' : ActorMethod<[string], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'recordScore' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveGameProgress' : ActorMethod<
    [bigint, Array<bigint>, Array<[bigint, bigint]>, Array<bigint>],
    undefined
  >,
  'saveLevelQuizScore' : ActorMethod<[bigint, bigint], undefined>,
  'searchStudyTips' : ActorMethod<[string], Array<StudyTip>>,
  'submitQuizAnswers' : ActorMethod<[bigint, Array<bigint>], bigint>,
  'updateLevelCompletion' : ActorMethod<[bigint], undefined>,
  'updatePomodoroSettings' : ActorMethod<[bigint, bigint], undefined>,
  'updateStudyPlan' : ActorMethod<
    [Array<Subject>, Array<string>, string],
    undefined
  >,
  'updateStudyTip' : ActorMethod<[bigint, string, string, Subject], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];