/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Subject = IDL.Variant({
  'reading' : IDL.Null,
  'socialStudies' : IDL.Null,
  'math' : IDL.Null,
  'grammar' : IDL.Null,
  'science' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Question = IDL.Record({
  'text' : IDL.Text,
  'correctAnswerIndex' : IDL.Nat,
  'options' : IDL.Vec(IDL.Text),
});
export const Note = IDL.Record({
  'id' : IDL.Nat,
  'subject' : Subject,
  'blob' : ExternalBlob,
  'description' : IDL.Text,
  'fileName' : IDL.Text,
  'uploadedBy' : IDL.Principal,
});
export const Quiz = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'subject' : Subject,
  'questions' : IDL.Vec(Question),
});
export const StudyTip = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'subject' : Subject,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : IDL.Text,
  'email' : IDL.Text,
});
export const GameProgress = IDL.Record({
  'quizScoresPerLevel' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat)),
  'userId' : IDL.Principal,
  'currentLevel' : IDL.Nat,
  'unlockedLevels' : IDL.Vec(IDL.Nat),
  'completedLevels' : IDL.Vec(IDL.Nat),
});
export const PomodoroSettings = IDL.Record({
  'focusTime' : IDL.Nat,
  'breakTime' : IDL.Nat,
});
export const QuizResult = IDL.Record({
  'userId' : IDL.Principal,
  'answers' : IDL.Vec(IDL.Nat),
  'score' : IDL.Nat,
  'totalQuestions' : IDL.Nat,
  'timestamp' : IDL.Int,
  'quizId' : IDL.Nat,
});
export const StudyPlan = IDL.Record({
  'timetable' : IDL.Text,
  'subjects' : IDL.Vec(Subject),
  'timeSlots' : IDL.Vec(IDL.Text),
  'userId' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addNote' : IDL.Func([ExternalBlob, Subject, IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'completeSubjectChallenge' : IDL.Func([IDL.Text], [], []),
  'createQuiz' : IDL.Func(
      [IDL.Text, Subject, IDL.Vec(Question)],
      [IDL.Nat],
      [],
    ),
  'createStudyPlan' : IDL.Func(
      [IDL.Vec(Subject), IDL.Vec(IDL.Text), IDL.Text],
      [],
      [],
    ),
  'createStudyTip' : IDL.Func([IDL.Text, IDL.Text, Subject], [IDL.Nat], []),
  'deleteNote' : IDL.Func([IDL.Nat], [], []),
  'deleteQuiz' : IDL.Func([IDL.Nat], [], []),
  'deleteStudyTip' : IDL.Func([IDL.Nat], [], []),
  'getAdminStatistics' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalStudyTips' : IDL.Nat,
          'totalQuizzes' : IDL.Nat,
          'totalNotes' : IDL.Nat,
          'totalUsers' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getAllNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
  'getAllQuizzes' : IDL.Func([], [IDL.Vec(Quiz)], ['query']),
  'getAllStudyTips' : IDL.Func([], [IDL.Vec(StudyTip)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getGameProgress' : IDL.Func([], [IDL.Opt(GameProgress)], ['query']),
  'getGameScores' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
  'getLeaderboard' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Nat))],
      ['query'],
    ),
  'getNotesBySubject' : IDL.Func([Subject], [IDL.Vec(Note)], ['query']),
  'getOverallProgress' : IDL.Func(
      [],
      [
        IDL.Record({
          'quizScores' : IDL.Vec(IDL.Nat),
          'gameProgressData' : IDL.Opt(GameProgress),
          'studyHours' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getPomodoroSettings' : IDL.Func([], [PomodoroSettings], ['query']),
  'getQuizResultsForQuiz' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(QuizResult)],
      ['query'],
    ),
  'getQuizResultsForUser' : IDL.Func([], [IDL.Vec(QuizResult)], ['query']),
  'getQuizzesBySubject' : IDL.Func([Subject], [IDL.Vec(Quiz)], ['query']),
  'getStudyPlan' : IDL.Func([], [IDL.Opt(StudyPlan)], ['query']),
  'getStudyTipsBySubject' : IDL.Func([Subject], [IDL.Vec(StudyTip)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'hasCompletedSubjectChallenge' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'recordScore' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveGameProgress' : IDL.Func(
      [
        IDL.Nat,
        IDL.Vec(IDL.Nat),
        IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat)),
        IDL.Vec(IDL.Nat),
      ],
      [],
      [],
    ),
  'saveLevelQuizScore' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'searchStudyTips' : IDL.Func([IDL.Text], [IDL.Vec(StudyTip)], ['query']),
  'submitQuizAnswers' : IDL.Func([IDL.Nat, IDL.Vec(IDL.Nat)], [IDL.Nat], []),
  'updateLevelCompletion' : IDL.Func([IDL.Nat], [], []),
  'updatePomodoroSettings' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'updateStudyPlan' : IDL.Func(
      [IDL.Vec(Subject), IDL.Vec(IDL.Text), IDL.Text],
      [],
      [],
    ),
  'updateStudyTip' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, Subject], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Subject = IDL.Variant({
    'reading' : IDL.Null,
    'socialStudies' : IDL.Null,
    'math' : IDL.Null,
    'grammar' : IDL.Null,
    'science' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Question = IDL.Record({
    'text' : IDL.Text,
    'correctAnswerIndex' : IDL.Nat,
    'options' : IDL.Vec(IDL.Text),
  });
  const Note = IDL.Record({
    'id' : IDL.Nat,
    'subject' : Subject,
    'blob' : ExternalBlob,
    'description' : IDL.Text,
    'fileName' : IDL.Text,
    'uploadedBy' : IDL.Principal,
  });
  const Quiz = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'subject' : Subject,
    'questions' : IDL.Vec(Question),
  });
  const StudyTip = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'subject' : Subject,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : IDL.Text,
    'email' : IDL.Text,
  });
  const GameProgress = IDL.Record({
    'quizScoresPerLevel' : IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat)),
    'userId' : IDL.Principal,
    'currentLevel' : IDL.Nat,
    'unlockedLevels' : IDL.Vec(IDL.Nat),
    'completedLevels' : IDL.Vec(IDL.Nat),
  });
  const PomodoroSettings = IDL.Record({
    'focusTime' : IDL.Nat,
    'breakTime' : IDL.Nat,
  });
  const QuizResult = IDL.Record({
    'userId' : IDL.Principal,
    'answers' : IDL.Vec(IDL.Nat),
    'score' : IDL.Nat,
    'totalQuestions' : IDL.Nat,
    'timestamp' : IDL.Int,
    'quizId' : IDL.Nat,
  });
  const StudyPlan = IDL.Record({
    'timetable' : IDL.Text,
    'subjects' : IDL.Vec(Subject),
    'timeSlots' : IDL.Vec(IDL.Text),
    'userId' : IDL.Principal,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addNote' : IDL.Func([ExternalBlob, Subject, IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'completeSubjectChallenge' : IDL.Func([IDL.Text], [], []),
    'createQuiz' : IDL.Func(
        [IDL.Text, Subject, IDL.Vec(Question)],
        [IDL.Nat],
        [],
      ),
    'createStudyPlan' : IDL.Func(
        [IDL.Vec(Subject), IDL.Vec(IDL.Text), IDL.Text],
        [],
        [],
      ),
    'createStudyTip' : IDL.Func([IDL.Text, IDL.Text, Subject], [IDL.Nat], []),
    'deleteNote' : IDL.Func([IDL.Nat], [], []),
    'deleteQuiz' : IDL.Func([IDL.Nat], [], []),
    'deleteStudyTip' : IDL.Func([IDL.Nat], [], []),
    'getAdminStatistics' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalStudyTips' : IDL.Nat,
            'totalQuizzes' : IDL.Nat,
            'totalNotes' : IDL.Nat,
            'totalUsers' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getAllNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
    'getAllQuizzes' : IDL.Func([], [IDL.Vec(Quiz)], ['query']),
    'getAllStudyTips' : IDL.Func([], [IDL.Vec(StudyTip)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getGameProgress' : IDL.Func([], [IDL.Opt(GameProgress)], ['query']),
    'getGameScores' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
    'getLeaderboard' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Nat))],
        ['query'],
      ),
    'getNotesBySubject' : IDL.Func([Subject], [IDL.Vec(Note)], ['query']),
    'getOverallProgress' : IDL.Func(
        [],
        [
          IDL.Record({
            'quizScores' : IDL.Vec(IDL.Nat),
            'gameProgressData' : IDL.Opt(GameProgress),
            'studyHours' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getPomodoroSettings' : IDL.Func([], [PomodoroSettings], ['query']),
    'getQuizResultsForQuiz' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(QuizResult)],
        ['query'],
      ),
    'getQuizResultsForUser' : IDL.Func([], [IDL.Vec(QuizResult)], ['query']),
    'getQuizzesBySubject' : IDL.Func([Subject], [IDL.Vec(Quiz)], ['query']),
    'getStudyPlan' : IDL.Func([], [IDL.Opt(StudyPlan)], ['query']),
    'getStudyTipsBySubject' : IDL.Func(
        [Subject],
        [IDL.Vec(StudyTip)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'hasCompletedSubjectChallenge' : IDL.Func(
        [IDL.Text],
        [IDL.Bool],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'recordScore' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveGameProgress' : IDL.Func(
        [
          IDL.Nat,
          IDL.Vec(IDL.Nat),
          IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat)),
          IDL.Vec(IDL.Nat),
        ],
        [],
        [],
      ),
    'saveLevelQuizScore' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'searchStudyTips' : IDL.Func([IDL.Text], [IDL.Vec(StudyTip)], ['query']),
    'submitQuizAnswers' : IDL.Func([IDL.Nat, IDL.Vec(IDL.Nat)], [IDL.Nat], []),
    'updateLevelCompletion' : IDL.Func([IDL.Nat], [], []),
    'updatePomodoroSettings' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'updateStudyPlan' : IDL.Func(
        [IDL.Vec(Subject), IDL.Vec(IDL.Text), IDL.Text],
        [],
        [],
      ),
    'updateStudyTip' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, Subject], [], []),
  });
};

export const init = ({ IDL }) => { return []; };